# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f018e16b6424c9723450bf27b95bfd2eebe620fe71cdde2c53926658d27b222894f9bef8d415384f87d630a00f2f57aef5f538bb00efdbcffdc63b9f7501779

test:
  secret_key_base: 931c5f8c7aa70ac49b3f0202cd15d8b371e90c1b3a02dc187c56229ca4ca1505acda853bf2809c2fb378098bb87389727a3efc7f2d3f54697cf7611e3acc7e8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
